# -*- coding: utf-8 -*-
"""ProjectQC1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weL2CDdPCBHwRHYA9sa8_L9iclHG1cmO
"""

import os
import time
import numpy as np
import matplotlib.pyplot as plt


# Paths
CUBE_PATH = "/content/indianpinearray.npy"
OUT_DIR = "/content/pca_outputs"
os.makedirs(OUT_DIR, exist_ok=True)


# Settings
K_LIST = [1, 2, 3, 5, 10, 15, 20, 30, 50]
RANDOM_SEED = 7
POWER_MAX_ITERS = 300
POWER_TOL = 1e-8


# Utilities
def load_data(cube_path):
    cube = np.load(cube_path).astype(np.float64)
    h, w, b = cube.shape
    X = cube.reshape(-1, b)
    return cube, X, h, w, b


def mean_center(X):
    mu = X.mean(axis=0, keepdims=True)
    Xc = X - mu
    return Xc, mu


def reconstruction_error(X_true, X_hat):
    return np.linalg.norm(X_true - X_hat, ord="fro") / (
        np.linalg.norm(X_true, ord="fro") + 1e-12
    )


def compression_ratio(n, d, k):
    return (n * d) / (k * (n + d))


def cumulative_explained_variance(eigvals):
    eigvals = np.maximum(eigvals, 0)
    evr = eigvals / (eigvals.sum() + 1e-12)
    return np.cumsum(evr)


# Method 1: PCA via EVD
def pca_evd(Xc, k_list):
    n, d = Xc.shape

    t0 = time.perf_counter()
    C = (Xc.T @ Xc) / (n - 1)
    eigvals, eigvecs = np.linalg.eigh(C)

    idx = np.argsort(eigvals)[::-1]
    eigvals = eigvals[idx]
    eigvecs = eigvecs[:, idx]

    total_time = time.perf_counter() - t0

    results = {}

    for k in k_list:
        W = eigvecs[:, :k]
        Z = Xc @ W
        X_hat = Z @ W.T

        err = reconstruction_error(Xc, X_hat)

        flops = 2 * n * d * d + d**3 + 4 * n * d * k

        results[k] = {
            "error": err,
            "runtime": total_time,
            "flops": flops,
            "eigvals": eigvals
        }

    return results


# Method 2: PCA via SVD
def pca_svd(Xc, k_list):
    n, d = Xc.shape

    t0 = time.perf_counter()
    U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
    total_time = time.perf_counter() - t0

    explained_variance = (S**2) / (n - 1)

    results = {}

    for k in k_list:
        Uk = U[:, :k]
        Sk = S[:k]
        Vtk = Vt[:k, :]

        X_hat = (Uk * Sk) @ Vtk

        err = reconstruction_error(Xc, X_hat)

        flops = 2 * n * d * d + 11 * d**3 + 2 * n * k * d

        results[k] = {
            "error": err,
            "runtime": total_time,
            "flops": flops,
            "eigvals": explained_variance
        }

    return results


# Method 3: PCA via Power Iteration
def top_eigenpair_power(A, max_iters=300, tol=1e-8, rng=None):
    d = A.shape[0]

    x = rng.normal(size=d)
    x = x / (np.linalg.norm(x) + 1e-12)

    num_iters = 0

    for _ in range(max_iters):
        y = A @ x
        y_norm = np.linalg.norm(y) + 1e-12
        x_new = y / y_norm

        num_iters += 1

        if np.linalg.norm(x_new - x) < tol:
            x = x_new
            break

        x = x_new

    lam = float(x.T @ A @ x)

    return lam, x, num_iters


def pca_power_iteration(Xc, k_list, max_iters=300, tol=1e-8, seed=7):
    n, d = Xc.shape
    rng = np.random.default_rng(seed)

    t0 = time.perf_counter()

    C = (Xc.T @ Xc) / (n - 1)
    A = C.copy()

    eigvals = []
    eigvecs = []
    total_iters = 0

    max_k = max(k_list)

    for _ in range(max_k):
        lam, v, iters_used = top_eigenpair_power(
            A,
            max_iters=max_iters,
            tol=tol,
            rng=rng
        )

        eigvals.append(lam)
        eigvecs.append(v)
        total_iters += iters_used

        A = A - lam * np.outer(v, v)

    eigvals = np.array(eigvals)
    eigvecs = np.column_stack(eigvecs)

    total_time = time.perf_counter() - t0

    results = {}

    for k in k_list:
        W = eigvecs[:, :k]
        Z = Xc @ W
        X_hat = Z @ W.T

        err = reconstruction_error(Xc, X_hat)

        avg_iters = max(1, total_iters / max_k)

        flops = (
            2 * n * d * d
            + k * (2 * d * d * avg_iters + d * d)
            + 4 * n * d * k
        )

        results[k] = {
            "error": err,
            "runtime": total_time,
            "flops": flops,
            "eigvals": eigvals
        }

    return results


# Plot 0: Cumulative Explained Variance
def plot_cumulative_variance_from_eigvals(eigvals, out_dir):
    cumulative_ratio = cumulative_explained_variance(eigvals)
    k_vals = np.arange(1, len(cumulative_ratio) + 1)

    plt.figure(figsize=(8, 5))

    plt.plot(
        k_vals,
        cumulative_ratio,
        marker="o",
        markersize=3,
        linewidth=2,
        label="Cumulative Explained Variance"
    )

    plt.xlabel("Number of Principal Components")
    plt.ylabel("Cumulative Explained Variance")
    plt.title("Cumulative Explained Variance")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    fpath = os.path.join(out_dir, "cumulative_variance.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# Plot 1: Reconstruction Error vs k
def plot_reconstruction_vs_k(all_results, k_list, out_dir):
    plt.figure(figsize=(8, 5))

    offsets = {
        "EVD": -0.001,
        "SVD": 0.0,
        "Power Iteration": 0.001
    }

    markers = {
        "EVD": "o",
        "SVD": "s",
        "Power Iteration": "^"
    }

    linestyles = {
        "EVD": "-",
        "SVD": "--",
        "Power Iteration": ":"
    }

    for method, res in all_results.items():
        errs = np.array([res[k]["error"] for k in k_list])
        errs_for_plot = errs + offsets[method]

        plt.plot(
            k_list,
            errs_for_plot,
            marker=markers[method],
            linestyle=linestyles[method],
            linewidth=2,
            label=method
        )

    plt.xlabel("Number of Components (k)")
    plt.ylabel("Relative Reconstruction Error")
    plt.title("Reconstruction Accuracy vs Number of Components")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure1_reconstruction_vs_k.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# Plot 2: Runtime Bar Chart
def plot_runtime_bar(all_results, chosen_k, out_dir):
    methods = list(all_results.keys())
    runtimes = [all_results[m][chosen_k]["runtime"] for m in methods]

    plt.figure(figsize=(7, 5))

    plt.bar(methods, runtimes)

    plt.ylabel("Runtime (seconds)")
    plt.title(f"Runtime Comparison at k = {chosen_k}")
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure2_runtime_bar.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# Plot 3: Compression Ratio vs Reconstruction Error
def plot_compression_vs_error(all_results, k_list, n, d, out_dir):
    plt.figure(figsize=(8, 5))

    offsets = {
        "EVD": -0.001,
        "SVD": 0.0,
        "Power Iteration": 0.001
    }

    markers = {
        "EVD": "o",
        "SVD": "s",
        "Power Iteration": "^"
    }

    linestyles = {
        "EVD": "-",
        "SVD": "--",
        "Power Iteration": ":"
    }

    for method, res in all_results.items():
        cr = np.array([compression_ratio(n, d, k) for k in k_list])
        errs = np.array([res[k]["error"] for k in k_list])
        errs_for_plot = errs + offsets[method]

        plt.plot(
            cr,
            errs_for_plot,
            marker=markers[method],
            linestyle=linestyles[method],
            linewidth=2,
            label=method
        )

    plt.xlabel("Compression Ratio")
    plt.ylabel("Relative Reconstruction Error")
    plt.title("Compression Ratio vs Reconstruction Error")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure3_compression_vs_error.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# Plot 4: FLOP Bar Chart
def plot_flops_bar(all_results, chosen_k, out_dir):
    methods = list(all_results.keys())
    flops = [all_results[m][chosen_k]["flops"] for m in methods]

    plt.figure(figsize=(7, 5))

    plt.bar(methods, flops)
    plt.yscale("log")

    plt.ylabel("Estimated FLOP Count (log scale)")
    plt.title(f"Complexity / FLOP Comparison at k = {chosen_k}")
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure4_flops_bar.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# Main
def main():
    cube, X, h, w, d = load_data(CUBE_PATH)
    Xc, mu = mean_center(X)
    n = Xc.shape[0]

    print("Cube shape:", cube.shape)
    print("Matrix shape:", X.shape)
    print("Centered matrix shape:", Xc.shape)

    evd_res = pca_evd(Xc, K_LIST)
    svd_res = pca_svd(Xc, K_LIST)

    power_res = pca_power_iteration(
        Xc,
        K_LIST,
        max_iters=POWER_MAX_ITERS,
        tol=POWER_TOL,
        seed=RANDOM_SEED
    )

    all_results = {
        "EVD": evd_res,
        "SVD": svd_res,
        "Power Iteration": power_res
    }

    chosen_k = 10

    eigvals = evd_res[1]["eigvals"]

    f0 = plot_cumulative_variance_from_eigvals(eigvals, OUT_DIR)
    f1 = plot_reconstruction_vs_k(all_results, K_LIST, OUT_DIR)
    f2 = plot_runtime_bar(all_results, chosen_k, OUT_DIR)
    f3 = plot_compression_vs_error(all_results, K_LIST, n, d, OUT_DIR)
    f4 = plot_flops_bar(all_results, chosen_k, OUT_DIR)

    print("\nSummary at k =", chosen_k)

    for method, res in all_results.items():
        print(
            f"{method:16s} | "
            f"error = {res[chosen_k]['error']:.6f} | "
            f"runtime = {res[chosen_k]['runtime']:.6f} sec | "
            f"flops = {res[chosen_k]['flops']:.3e}"
        )

    print("\nSaved figures:")
    for f in [f0, f1, f2, f3, f4]:
        print(f)


if __name__ == "__main__":
    main()

# Extra diagnostics for Power Iteration:
# 1) Iteration count per extracted component
# 2) Residual convergence history
#This behavior is consistent with high-dimensional factor models,
#where weak factors lead to slower convergence of iterative PCA
#methods
#In practice, this can lead to apparent non-convergence within
#a fixed iteration budget, as observed in this experiment.

POWER_DIAG_K = 10


def top_eigenpair_power_with_history(A, max_iters=300, tol=1e-8, rng=None):
    d = A.shape[0]

    if rng is None:
        rng = np.random.default_rng(7)

    x = rng.normal(size=d)
    x = x / (np.linalg.norm(x) + 1e-12)

    iterate_diffs = []
    residuals = []

    A_norm = np.linalg.norm(A, ord="fro") + 1e-12

    for _ in range(max_iters):
        y = A @ x
        y_norm = np.linalg.norm(y) + 1e-12
        x_new = y / y_norm

        lam_new = float(x_new.T @ A @ x_new)

        iterate_diff = np.linalg.norm(x_new - x)
        residual = np.linalg.norm(A @ x_new - lam_new * x_new) / A_norm

        iterate_diffs.append(iterate_diff)
        residuals.append(residual)

        x = x_new

        if iterate_diff < tol:
            break

    lam = float(x.T @ A @ x)

    return lam, x, len(iterate_diffs), iterate_diffs, residuals


def power_iteration_diagnostics(Xc, k=10, max_iters=300, tol=1e-8, seed=7):
    n, d = Xc.shape
    rng = np.random.default_rng(seed)

    C = (Xc.T @ Xc) / (n - 1)
    A = C.copy()

    eigvals = []
    iteration_counts = []
    iterate_diff_histories = []
    residual_histories = []

    for component in range(1, k + 1):
        lam, v, iters, diffs, residuals = top_eigenpair_power_with_history(
            A,
            max_iters=max_iters,
            tol=tol,
            rng=rng
        )

        eigvals.append(lam)
        iteration_counts.append(iters)
        iterate_diff_histories.append(diffs)
        residual_histories.append(residuals)

        A = A - lam * np.outer(v, v)

    diagnostics = {
        "eigvals": np.array(eigvals),
        "iteration_counts": iteration_counts,
        "iterate_diff_histories": iterate_diff_histories,
        "residual_histories": residual_histories
    }

    return diagnostics


def plot_power_iteration_counts(diagnostics, out_dir):
    iteration_counts = diagnostics["iteration_counts"]
    components = np.arange(1, len(iteration_counts) + 1)

    plt.figure(figsize=(8, 5))

    plt.bar(components, iteration_counts)

    for x, y in zip(components, iteration_counts):
        plt.text(
            x,
            y + 1,
            str(y),
            ha="center",
            va="bottom",
            fontsize=9
        )

    plt.xlabel("Principal Component Index")
    plt.ylabel("Number of Iterations to Converge")
    plt.title("Power Iteration Convergence Count per Component")
    plt.xticks(components)
    plt.grid(True, axis="y", alpha=0.3)
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure5_power_iteration_counts.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


def plot_power_iteration_residuals(diagnostics, out_dir):
    residual_histories = diagnostics["residual_histories"]

    plt.figure(figsize=(8, 5))

    selected_components = [1, 2, 3, 5, 10]

    for component in selected_components:
        if component <= len(residual_histories):
            residuals = residual_histories[component - 1]
            iterations = np.arange(1, len(residuals) + 1)

            plt.semilogy(
                iterations,
                residuals,
                linewidth=2,
                label=f"Component {component}"
            )

    plt.xlabel("Iteration Number")
    plt.ylabel("Relative Eigen-Residual")
    plt.title("Power Iteration Residual Convergence")
    plt.grid(True, alpha=0.3, which="both")
    plt.legend()
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure6_power_iteration_residuals.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


def plot_power_iteration_iterate_differences(diagnostics, out_dir):
    iterate_diff_histories = diagnostics["iterate_diff_histories"]

    plt.figure(figsize=(8, 5))

    selected_components = [1, 2, 3, 5, 10]

    for component in selected_components:
        if component <= len(iterate_diff_histories):
            diffs = iterate_diff_histories[component - 1]
            iterations = np.arange(1, len(diffs) + 1)

            plt.semilogy(
                iterations,
                diffs,
                linewidth=2,
                label=f"Component {component}"
            )

    plt.axhline(
        POWER_TOL,
        linestyle="--",
        linewidth=1.5,
        label=f"Tolerance = {POWER_TOL:.0e}"
    )

    plt.xlabel("Iteration Number")
    plt.ylabel(r"$\|x^{(t+1)} - x^{(t)}\|_2$")
    plt.title("Power Iteration Iterate-Difference Convergence")
    plt.grid(True, alpha=0.3, which="both")
    plt.legend()
    plt.tight_layout()

    fpath = os.path.join(out_dir, "figure7_power_iteration_iterate_differences.png")
    plt.savefig(fpath, dpi=300)
    plt.close()

    return fpath


# after main section run it

cube, X, h, w, d = load_data(CUBE_PATH)
Xc, mu = mean_center(X)

power_diag = power_iteration_diagnostics(
    Xc,
    k=POWER_DIAG_K,
    max_iters=POWER_MAX_ITERS,
    tol=POWER_TOL,
    seed=RANDOM_SEED
)

f5 = plot_power_iteration_counts(power_diag, OUT_DIR)
f6 = plot_power_iteration_residuals(power_diag, OUT_DIR)
f7 = plot_power_iteration_iterate_differences(power_diag, OUT_DIR)

print("\nPower Iteration Diagnostics")
print("Component | Iterations | Final Residual | Final Iterate Difference")

for i in range(POWER_DIAG_K):
    final_residual = power_diag["residual_histories"][i][-1]
    final_diff = power_diag["iterate_diff_histories"][i][-1]

    print(
        f"{i + 1:9d} | "
        f"{power_diag['iteration_counts'][i]:10d} | "
        f"{final_residual:14.6e} | "
        f"{final_diff:22.6e}"
    )

print("\nSaved diagnostic figures:")
print(f5)
print(f6)
print(f7)

# Combined visualization: bands + RGB + histogram in one figure
#how the data look like before dimensionality reduction
import numpy as np
import matplotlib.pyplot as plt

# CHANGE PATH
CUBE_PATH = "indianpinearray.npy"


# load data
cube = np.load(CUBE_PATH).astype(np.float64)
h, w, b = cube.shape

# bands to display
bands_to_show = [0, 50, 100]

# RGB bands
r_band, g_band, b_band = 50, 30, 10

# create RGB image
rgb = np.stack([
    cube[:, :, r_band],
    cube[:, :, g_band],
    cube[:, :, b_band]
], axis=-1)

# normalize RGB
rgb = (rgb - rgb.min()) / (rgb.max() - rgb.min() + 1e-12)

# ---- plotting ----
plt.figure(figsize=(14, 8))

# --- row 1: spectral bands ---
for i, band in enumerate(bands_to_show):
    plt.subplot(2, 3, i + 1)
    plt.imshow(cube[:, :, band], cmap='viridis')
    plt.title(f"Band {band}")
    plt.axis('off')

# --- row 2: RGB + histogram ---
# RGB
plt.subplot(2, 3, 4)
plt.imshow(rgb)
plt.title("Pseudo-RGB")
plt.axis('off')

# histogram
plt.subplot(2, 3, 5)
plt.hist(cube.flatten(), bins=50)
plt.title("Pixel Intensity Distribution")
plt.xlabel("Intensity")
plt.ylabel("Frequency")

# empty slot (optional)
plt.subplot(2, 3, 6)
plt.axis('off')

plt.suptitle("Original Hyperspectral Data Visualization (Before PCA)")
plt.tight_layout()

plt.savefig("combined_original_visualization.png", dpi=300)
plt.show()

# pca_k10_visualization.py
# Visualization of hyperspectral data after PCA with k = 10


# What we already have
# X  : (N x B) reshaped data
# h, w : original spatial dimensions
# Xc : mean-centered data



# CHANGE PATH
CUBE_PATH = "indianpinearray.npy"


def load_data(path):
    cube = np.load(path).astype(np.float64)
    h, w, b = cube.shape
    X = cube.reshape(-1, b)
    return cube, X, h, w, b

def mean_center(X):
    mu = X.mean(axis=0, keepdims=True)
    return X - mu, mu

def main():
    cube, X, h, w, d = load_data(CUBE_PATH)
    Xc, mu = mean_center(X)

    k = 10

    # PCA via SVD
    U, S, Vt = np.linalg.svd(Xc, full_matrices=False)

    # projection
    Z_k = Xc @ Vt[:k].T

    # reconstruction
    Xk = Z_k @ Vt[:k]

    # reshape back to image cube
    Xk_cube = Xk.reshape(h, w, d)

    # plot reconstructed bands
    bands_to_show = [0, 10, 50, 100, 150]

    plt.figure(figsize=(12, 6))
    for i, b in enumerate(bands_to_show):
        plt.subplot(2, 3, i + 1)
        plt.imshow(Xk_cube[:, :, b], cmap='viridis')
        plt.title(f"Band {b}")
        plt.axis('off')

    plt.suptitle("Reconstructed Hyperspectral Bands (k = 10)")
    plt.tight_layout()
    plt.savefig("reconstructed_bands_k10.png", dpi=300)
    plt.close()

    # compare original vs reconstructed
    band = 50
    orig = cube[:, :, band]
    recon = Xk_cube[:, :, band]

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(orig, cmap='viridis')
    plt.title("Original")
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(recon, cmap='viridis')
    plt.title("Reconstructed (k=10)")
    plt.axis('off')

    plt.suptitle(f"Band {band} Comparison")
    plt.tight_layout()
    plt.savefig("comparison_band50_k10.png", dpi=300)
    plt.close()

    # PCA spectral components
    plt.figure(figsize=(12, 6))
    for i in range(k):
        plt.subplot(2, 5, i + 1)
        plt.plot(Vt[i])
        plt.title(f"PC {i+1}")
        plt.xticks([])
        plt.yticks([])

    plt.suptitle("Top 10 Principal Components")
    plt.tight_layout()
    plt.savefig("pca_components_k10.png", dpi=300)
    plt.close()

    print("Saved files:")
    print("- reconstructed_bands_k10.png")
    print("- comparison_band50_k10.png")
    print("- pca_components_k10.png")


if __name__ == "__main__":
    main()

# combined plot version how the data look like after the dimensionality reduction


plt.figure(figsize=(16, 12))

# Row 1: Reconstructed Bands
bands_to_show = [0, 10, 50, 100, 150]

for i, b in enumerate(bands_to_show):
    plt.subplot(4, 5, i + 1)
    plt.imshow(Xk_cube[:, :, b], cmap='viridis')
    plt.title(f"Band {b}")
    plt.axis('off')

# Row 2: Original vs Reconstructed
band = 50

plt.subplot(4, 5, 6)
plt.imshow(cube[:, :, band], cmap='viridis')
plt.title("Original")
plt.axis('off')

plt.subplot(4, 5, 7)
plt.imshow(Xk_cube[:, :, band], cmap='viridis')
plt.title("Reconstructed")
plt.axis('off')

# empty spaces for alignment
for i in range(8, 11):
    plt.subplot(4, 5, i)
    plt.axis('off')

# Rows 3 & 4: PCA Components
for i in range(10):
    plt.subplot(4, 5, 11 + i)
    plt.plot(Vt[i])
    plt.title(f"PC {i+1}", fontsize=8)
    plt.xticks([])
    plt.yticks([])

# Final layout
plt.suptitle("PCA Visualization (k = 10): Bands, Reconstruction, and Components")
plt.tight_layout()

plt.savefig("combined_pca_k10_visualization.png", dpi=300)
plt.show()